[package]
name = "example"
version = "0.1.0"
authors = ["blackredscarf <blackredscarf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloomf = { path="../" }
#bloomf = "0.1.0"
bytes="0.6.0"