[package]
name = "bloom-filter"
version = "0.1.0"
license = "MIT"
description = "Bloom Filter"
authors = ["blackredscarf <blackredscarf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes="0.6.0"